# Generated by Django 5.2.5 on 2025-09-11 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField(default=0.0)),
                ('confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='chat.documentchunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['-similarity'],
                'indexes': [models.Index(fields=['message'], name='chat_chatme_message_ca6f49_idx'), models.Index(fields=['chunk'], name='chat_chatme_chunk_i_bcad1d_idx')],
            },
        ),
    ]
