# Generated by Django 5.2.5 on 2025-09-17 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ease_of_use', models.CharField(choices=[('easy', 'Easy'), ('neutral', 'Neutral'), ('difficult', 'Difficult')], max_length=16)),
                ('relevance', models.CharField(choices=[('relevant', 'Relevant'), ('neutral', 'Neutral'), ('not_relevant', 'Not relevant')], max_length=16)),
                ('trust', models.CharField(choices=[('confident', 'Confident'), ('neutral', 'Neutral'), ('not_confident', 'Not confident')], max_length=16)),
                ('citations_helpfulness', models.CharField(choices=[('helpful', 'Helpful'), ('neutral', 'Neutral'), ('not_helpful', 'Not helpful')], max_length=16)),
                ('likelihood_of_use', models.CharField(choices=[('likely', 'Likely'), ('neutral', 'Neutral'), ('unlikely', 'Unlikely')], max_length=16)),
                ('additional_sources', models.TextField(blank=True, null=True)),
                ('open_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='chat_survey_created_f50ef7_idx')],
            },
        ),
    ]
