# Generated by Django 5.2.5 on 2025-09-26 06:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_aboutcontent_howitworkscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Rich text content for the About page'),
        ),
        migrations.AlterField(
            model_name='howitworkscontent',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Rich text content for the How It Works page'),
        ),
    ]
